package com.voicenote.domain;

public enum EventType {
    TRANSCRIPTION_REQUESTED,
    DOCUMENT_ORGANIZATION_REQUESTED,
    ANALYSIS_REQUESTED,
    SPEAKER_CORRECTION_REQUESTED,
    KNOWLEDGE_INDEX_REQUESTED,
    KNOWLEDGE_RUN_REQUESTED,
    MEMORY_EXTRACTION_REQUESTED,
    CONVERSATION_SUMMARY_REQUESTED,
    USER_MEMORY_INDEX_REQUESTED,
    USER_MEMORY_DELETE_REQUESTED,
    PROGRESS_CHANGED
}
