package com.voicenote.domain;

public enum EventType {
    TRANSCRIPTION_REQUESTED,
    DOCUMENT_ORGANIZATION_REQUESTED,
    ANALYSIS_REQUESTED,
    KNOWLEDGE_INDEX_REQUESTED,
    KNOWLEDGE_RUN_REQUESTED,
    PROGRESS_CHANGED
}
