package com.voicenote.domain;

public enum PipelineStage {
    UPLOAD_COMPLETED,
    ASR_SUBMIT,
    ASR_POLL,
    TRANSCRIPT_PERSIST,
    RAW_DOCUMENT_READY,
    DOCUMENT_ORGANIZATION,
    FORMAL_DOCUMENT_READY,
    KNOWLEDGE_PREPARE,
    KNOWLEDGE_INDEX,
    COMPLETED
}
